Repository TexusDev/Texus, pull requests merged in 2021-11, with the labels that each got.

#2 Update README.rst
  README.rst
Labels: semver:patch, p:high, chore, backlog

#9 Slash command implementation
  discord/application/__init__.py
  discord/application/command.py
  discord/application/context.py
  discord/application/errors.py
  discord/enums.py
  discord/errors.py
Labels: semver:minor, p:high, feature, chore, discord, api support

#8 V2.1.0
  discord/__init__.py
  discord/application/__init__.py
  discord/application/command.py
  discord/application/context.py
  discord/application/errors.py
  discord/application/permissions.py
  discord/enums.py
  discord/errors.py
  discord/utils.py
Labels: version, semver:minor, p:high, feature, discord, api changes, api support

#12 Make send an alias for respond
  discord/commands/context.py
Labels: semver:patch, p:low, chore, backlog

#16 Create readme.md
  examples/replit/readme.md
Labels: p:low, api support

#17 Create .replit
  examples/replit/.replit
Labels: semver:patch, p:low, chore, backlog
